version: '3.8'

networks:
  mynetwork:
    driver: bridge

services:
  productcatalogapi:
    image: sfilipovski/product-catalog-api:latest
    build:
       context: .
       dockerfile: ProductCatalogAPI/Dockerfile
    container_name: productcatalogapi
    ports:
      - "8080:8080"
      - "8081:8081"
    networks:
      - mynetwork
    env_file:
      - .env
    depends_on:
      - mongo
    restart: always

  mongo:
    image: mongo:latest
    container_name: mongodb-cont
    command: mongod --auth --bind_ip_all
    ports:
      - 27017:27017
    volumes:
      - mongo_db_data:/data/db
      - ./init-mongo.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    environment:
      MONGO_INITDB_DATABASE: ${DATABASE_NAME}
      MONGO_INITDB_ROOT_USERNAME: ${DATABASE_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${DATABASE_PASSWORD}
    networks:
      - mynetwork
    env_file:
      - .env

volumes:
  mongo_db_data:
    driver: local
