on: [push]

name: Azure login workflow

jobs:

  login:
    runs-on: ubuntu-latest
    steps:
      - name: Azure Login
        uses: Azure/login@v2.2.0
        with:
          creds: ${{secrets.AZURE_CREDENTIALS}}
    
